### ISSUE TITLE
Spotify song not playing and not supported by queue

### ISSUE THREAD

**Issue by samchouse** [Lavaclient/plugins#2]
When trying to play the bot doesn't make any sounds
```
    if (this.client.manager.spotify.isSpotifyUrl(query)) {
      const item = await this.client.manager.spotify.load(query);
      if (item instanceof SpotifyTrack) {
        if (!player.connected)
          message.guild!.player!.connect(message.member!.voice.channel.id, {
            selfDeaf: true
          });

        player.setVolume(100);

        return player.play(item);
      }
    }
  ```
  
When using in queue I get this error
```
?play https://open.spotify.com/track/6wQlQrTY5mVS8EGaFZVwVF?si=24fdb4c246a145fb | Cannot read property 'buffer' of undefined
TypeError: Cannot read property 'buffer' of undefined
    at new DataInput (/home/xenfo/Desktop/Projects/discord-bots/muz/node_modules/.pnpm/@lavalink+encoding@0.1.1/node_modules/@lavalink/encoding/dist/src/DataInput.js:11:40)
    at Object.decode (/home/xenfo/Desktop/Projects/discord-bots/muz/node_modules/.pnpm/@lavalink+encoding@0.1.1/node_modules/@lavalink/encoding/dist/src/index.js:110:19)
    at new Song (/home/xenfo/Desktop/Projects/discord-bots/muz/node_modules/.pnpm/@lavaclient+queue@1.0.3/node_modules/@lavaclient/queue/dist/Song.js:9:36)
    at Queue.add (/home/xenfo/Desktop/Projects/discord-bots/muz/node_modules/.pnpm/@lavaclient+queue@1.0.3/node_modules/@lavaclient/queue/dist/Queue.js:66:25)
    at PlayCommand.exec (/home/xenfo/Desktop/Projects/discord-bots/muz/dist/src/bot/commands/music/Play.js:53:37)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async CommandHandler.runCommand (/home/xenfo/Desktop/Projects/discord-bots/muz/node_modules/.pnpm/discord-akairo@8.1.0/node_modules/discord-akairo/src/struct/commands/CommandHandler.js:768:25)
    at async CommandHandler.handleDirectCommand (/home/xenfo/Desktop/Projects/discord-bots/muz/node_modules/.pnpm/discord-akairo@8.1.0/node_modules/discord-akairo/src/struct/commands/CommandHandler.js:439:20)
    at async CommandHandler.handle (/home/xenfo/Desktop/Projects/discord-bots/muz/node_modules/.pnpm/discord-akairo@8.1.0/node_modules/discord-akairo/src/struct/commands/CommandHandler.js:379:23)
```

**Comment by birongliu** [comment]
There are a method in Spotify Manager call isSpotifyUrl to check if it a spotify url if so you can resolve the track. And it good idea to join lavaclient support server 😀

**Comment by samchouse** [comment]
I am checking if it's a Spotify URL and I'll be joining the support server shortly!

Edit: the support server's link is expired.

**Comment by samchouse** [comment]
Solved by resolving Youtube url

**Comment by viztea** [comment]
Sorry, https://discord.gg/CH9ubGPMV6
